config/routes.rb
Rails.application.routes.draw do
  resources :dynamites

  devise_for :users
  root 'pages#home'
	get 'about' => 'pages#about'

end

app/models/dynamite.rb
class Dynamite < ActiveRecord::Base
	validates :content, presence: true
	
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :dynamites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dynamites_controller.rb
class DynamitesController < ApplicationController
  before_action :set_dynamite, only: [:show, :edit, :update, :destroy]
	before_filter :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
	
  respond_to :html

  def index
    @dynamites = Dynamite.all
    respond_with(@dynamites)
  end

  def show
    respond_with(@dynamite)
  end

  def new
    @dynamite = Dynamite.new
    respond_with(@dynamite)
  end

  def edit
  end

  def create
    @dynamite = Dynamite.new(dynamite_params)
		@dynamite.user_id = current_user.id
    @dynamite.save
    respond_with(@dynamite)
  end

  def update
    @dynamite.update(dynamite_params)
    respond_with(@dynamite)
  end

  def destroy
    @dynamite.destroy
    respond_with(@dynamite)
  end

  private
    def set_dynamite
      @dynamite = Dynamite.find(params[:id])
    end

    def dynamite_params
      params.require(:dynamite).permit(:content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
	def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dynamites_helper.rb
module DynamitesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dynamites/_form.html.erb
<%= simple_form_for(@dynamite) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dynamites/edit.html.erb
<h1>Editing dynamite</h1>

<%= render 'form' %>

<%= link_to 'Show', @dynamite %> |
<%= link_to 'Back', dynamites_path %>

app/views/dynamites/index.html.erb
<h1>The Launching Pad</h1>

    <% @dynamites.each do |dynamite| %>
      
      <div class="panel panel-default">
				<div class="panel-body">
					
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-body">
					<%= dynamite.content %> 
					
				</div>
				<div class="panel-footer">sent by <%= dynamite.user.email %><%= link_to "<i class='fa fa-trash-o'></i>", dynamite, method: :delete, data: { confirm: 'Are you sure?' } %></div>
			</div>
    <% end %>

<br>

<%= link_to 'New Dynamite', new_dynamite_path %>

app/views/dynamites/new.html.erb
<h1>New dynamite</h1>

<%= render 'form' %>

<%= link_to 'Back', dynamites_path %>

app/views/dynamites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @dynamite.content %>
</p>

<%= link_to 'Edit', edit_dynamite_path(@dynamite) %> |
<%= link_to 'Back', dynamites_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<% if current_user %>
			<%= link_to "<i class='fa fa-university'></i> On Blast".html_safe, dynamites_path, class: "navbar-brand" %>
			<% else %>	
  		<%= link_to "<i class='fa fa-university'></i> On Blast".html_safe, root_path, class: "navbar-brand" %>
			<% end %>
</div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
				<% if current_user %>
					<li><%= link_to "Settings", edit_user_registration_path %></li>
					<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "About", about_path %></li>
					<li><%= link_to "Login", new_user_session_path %></li>
				<% end %>
			</ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>On Blast</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
<%= yield %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h2>About Us</h2>

app/views/pages/home.html.erb
<div class="jumbotron">
		<h1>Put them on Blast</h1>
		<p>The greatest and latest Twitter clone ever created by the one and only <a href="http://github.com/shelbsimone/bullhorn.git">shelbsimone</a>				<% if current_user %>
			
			<%= link_to "Drop Blasts", new_dynamite_path, class: "btn btn-primary btn-lg" %>
			
				<% else %>
			
		<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  <% end %>
</div>